version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=${JWT_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
